### ISSUE TITLE
Clients not picking up server stoppages (server hosted in Unity3D game)

### ISSUE THREAD

**Issue by mpenna** [bigqio/bigq#7] opened 2019-09-03 15:28 UTC
Hi @jchristn I know this is a bit off, but I'm trying to embed/host the server on a Unity3D app and I'm having a bit of an issue trying to debug why connected clients (ClientTest app) are not identifying whenever the server stops. I have ported all the server code and dependent libraries over to Unity3D and it seems to be working fine. I can start and stop the server and I can connect and disconnect clients. All corresponding events are detected and raised. Monitoring the ports via the Windows console while performing these operations also looks good. Server listener port and exchange ports are all being opened and closed. However, whenever I stop the server while clients are still connected, these do not pick up that the server has gone down -- as they normally do when we run the server on the Windows console host (ServerTest). Any ideas? This is the MonoBehaviour class where I'm instantiating and destroying the server instance: 

```C#
using BigQ.Core;
using BigQ.Server;
using UnityEngine;

public class ServerHost : MonoBehaviour
{
    private ServerConfiguration config;
    private Server server;

    void Start()
    {
        StartServer();
    }

    void OnDestroy()
    {
        // then I tried explicitly fetching and disposing the clients... didn't work either
        var clients = server.ListClients();
        if (clients != null)
        {
            foreach (var serverClient in clients)
            {
                serverClient.Dispose();
            }
        }

        // my first attempt was at disposing the server instance but it didn't work
        server?.Dispose();
    }

    #region Delegates

    private bool StartServer()
    {
        Debug.Log("Attempting to start server...");

        server?.Dispose();
        server = null;

        config = ServerConfiguration.Default();
        config.TcpServer.Debug = true;

        server = new Server(config)
        {
            Callbacks =
            {
                MessageReceived = MessageReceived,
                //ServerStopped = StartServer,
                ClientConnected = ClientConnected,
                ClientLogin = ClientLogin,
                ClientDisconnected = ClientDisconnected
            }
        };

        Debug.Log($"Server running at {config.TcpServer.Ip}:{config.TcpServer.Port}");

        return true;
    }

    private bool MessageReceived(Message msg)
    {
        Debug.Log(msg.ToString());
        return true;
    }

    private bool ClientConnected(ServerClient client)
    {
        Debug.Log($"[ClientConnected] received notice of connection of client from {client.IpPort}");
        return true;
    }

    private bool ClientLogin(ServerClient client)
    {
        Debug.Log($"[ClientLogin] received notice of client login GUID {client.ClientGUID} from {client.IpPort}");
        return true;
    }

    private bool ClientDisconnected(ServerClient client)
    {
        Debug.Log(
            $"[ClientDisconnected] received notice of disconnection of client GUID {client.ClientGUID} from {client.IpPort}");
        return true;
    }

    #endregion
}
```

Whenever the server stops, if we inspect the ports on the Windows console, we can see that both exchange ports are remain stuck in a "wait" state. Waiting, I believe, for a confirmation from the server, which never comes: 

  TCP    127.0.0.1:3314         127.0.0.1:8000         CLOSE_WAIT      9696
  TCP    127.0.0.1:8000         127.0.0.1:3314         FIN_WAIT_2      15692

**Comment by jchristn** [comment] 2019-09-03 15:40
Hi @mpenna just wanted to let you know this issue is received and acknowledged. Will be able to look at this tonight!  On a related note do you have the same issue with WatsonTcp, which is the underlying TCP implementation?

**Comment by mpenna** [comment] 2019-09-03 15:57
Thanks. I'm not sure what you mean by the underlying TCP impl, but I'm starting the TCP version of the server, so I guess it's WatsonTcp. The library has been imported into the project and it's being properly detected and loaded. BTW, before all this, I tried your Mesh library/package, but I was facing these same issues -- clients were not detecting when the server went down/stopped. 

On another note (perhaps related to this same issue): just now I have tested running more client instances concurrently. I was noticed that every new client took considerably longer to connect. The third client actually timed-out trying to connect the first time around, and eventually was able to connect.

**Comment by mpenna** [comment] 2019-09-03 16:01
Regarding the aforementioned Mesh attempt:  what I meant was that nodes were not detecting when the corresponding peer-nodes they were connected to went down/stopped. 

I guess it's a more proper wording for the issue.

**Comment by jchristn** [comment] 2019-09-03 16:01
Thanks @mpenna this is helpful. Did you mention this is running in Mono?  If so are you by chance using the ahead of time compiler?  I’ve found mixed results on projects running in Mono where the AOT compiler was not used. Sorry I won’t be able the computer til later to debug this. Cheers

**Comment by mpenna** [comment] 2019-09-03 16:04
I'm using the "net462" version of the libs, and I have configured Unity3D to use the .NET 4x API compatibility level. I'm running all this on Windows (but eventually I'll try an Android build).

**Comment by mpenna** [comment] 2019-09-03 16:12
The MonoBehaviour class is Unity3D's base class for scripts that are to be "attached" to "game objects". It declares a couple of props and methods that script author can use to affect the game object and Unity3D takes care of lifecylce management. The Start() method is much like a constructor function and the OnDestroy() would be pretty much the equivalent of a destructor.

**Comment by jchristn** [comment] 2019-09-03 22:12
Hi @mpenna sorry for the delay on this.  I just tested the underlying TCP implementation (WatsonTcp) under various termination scenarios and the client callback seems to be firing correctly (```WatsonTcpClient.ServerDisconnected```).  This callback is tied in BigQ to ```Client.Callbacks.ServerDisconnected```.  

Could you show me a snippet of the client initialization code?  If you've attached something to ```Client.Callbacks.ServerDisconnected``` and it isn't picking up on the disconnect then we should definitely do a deeper analysis.  Also if you're comfortable with it I'm happy to clone your repo and add my own logging/instrumentation to test, if that would make things easier for you.  Cheers!

**Comment by mpenna** [comment] 2019-09-03 23:18
Hi @jchristn No problem. I'm currently testing this scenario with your own ClientTest app. But just to be sure, this is the MaintainConnection background task which initializes, configures and keeps the client connected: 

```C#
        static void MaintainConnection()
        {
            bool firstRun = true;

            while (true)
            {
                if (firstRun)
                {

                }
                else
                {
                    firstRun = false;
                    Thread.Sleep(5000);
                }

                if (config == null)
                {
                    config = ClientConfiguration.Default();
                    config.ClientGUID = Guid.NewGuid().ToString();
                    config.Email = config.ClientGUID;
                    config.Name = config.ClientGUID;
                    config.ServerGUID = "00000000-0000-0000-0000-000000000000";
                    config.SyncTimeoutMs = 30000;

                    config.TcpServer = new ClientConfiguration.TcpServerSettings();
                    config.TcpServer.Debug = true;
                    config.TcpServer.Enable = true;
                    config.TcpServer.Ip = "127.0.0.1";
                    config.TcpServer.Port = 8000;
                }

                if (client == null || !client.Connected || !client.LoggedIn)
                {
                    try
                    {
                        Console.WriteLine("Attempting to connect to server");
                        if (client != null) client.Dispose();
                        
                        client = new Client(config);
                        
                        client.Callbacks.AsyncMessageReceived = AsyncMessageReceived;
                        client.Callbacks.SyncMessageReceived = SyncMessageReceived;
                        client.Callbacks.ServerDisconnected = ServerDisconnected;
                        client.Callbacks.ServerConnected = ServerConnected;
                        client.Callbacks.ClientJoinedServer = ClientJoinedServer;
                        client.Callbacks.ClientLeftServer = ClientLeftServer;
                        client.Callbacks.ClientJoinedChannel = ClientJoinedChannel;
                        client.Callbacks.ClientLeftChannel = ClientLeftChannel;
                        client.Callbacks.SubscriberJoinedChannel = SubscriberJoinedChannel;
                        client.Callbacks.SubscriberLeftChannel = SubscriberLeftChannel;
                        client.Callbacks.ChannelCreated = ChannelCreated;
                        client.Callbacks.ChannelDestroyed = ChannelDestroyed;

                        Console.WriteLine("Client connected, logging in");
                        Message response;
                        if (!client.Login(out response))
                        {
                            Console.WriteLine("Unable to login, retrying");
                        }
                    }
                    catch (Exception e)
                    {
                        PrintException("MaintainConnection", e);
                    }
                }
            }
        }
         
        static bool ServerDisconnected()
        {
            Console.WriteLine("Server disconnected");
            return true;
        }

```

The ServerDisconnected client callback is tied to the static function ServerDisconnected, Apparentely everything seems normal on the client side, but for some reason the handler is not being called/invoked.

**Comment by jchristn** [comment] 2019-09-03 23:26
Ok - I think I'm starting to understand.  This is pretty easy to reproduce.  I started ServerTest, started ClientTest, allowed ClientTest to connect, then dumped the server.  I see the reconnect attempt, and restart the server after the reconnect attempt has begun, which causes MaintainConnection to apparently seize.  

I think to resolve this, I'll need to amend WatsonTcp to allow the requestor to specify a timeout on a connection attempt.  I should be able to get to this tonight, and if not tonight, then tomorrow.  

Please let me know if I've misunderstood what you're experiencing!

**Comment by mpenna** [comment] 2019-09-03 23:37
I'm not sure if that is the situation or scenario I'm experiencing. I myself haven't detected the situation you described (the one happening between ServerTest and ClientTest apps). Last time I ran these two sample apps together they apparentely worked OK in tandem. However, if you noticed something odd while hunting down this issue, even better! What I'm experiencing here is some oddness with either the server not being able to trigger a client disconnection when stoping/closing the host app (Uniyt3D) or the client not being able to detect or receive such an event. If you guide me through the code to the exact point where the server is supposed to teardown its client connections, then I should be able to better debug this issue.

**Comment by mpenna** [comment] 2019-09-03 23:42
I'm not super expert in the inner-guts of TCP, but by the looks of the state the exchange ports are left in when the server goes down, I guess the server broke before being able to send the last ACK during the disconnection handshake.

**Comment by mpenna** [comment] 2019-09-03 23:48
Going through my last comment once again, one thing came to mind that I hadn't thought of before. Could it be that by invoking the Dispose() method on the server in order to trigger the whole teardown process the host app is somehow garbage-collecting the server instance before it has a chance to fully complete the teardown process?

**Comment by jchristn** [comment] 2019-09-03 23:57
Hi @mpenna the server doesn't really tear down the connections per se.  The underlying TCP and websocket servers are instances of WatsonTcp and WatsonWebsocket, which have callbacks should a client disconnect.  These point back to ```WatsonClientDisconnect``` within ```Server.cs``` which in turn calls ```DestroyClient```, which does a ```.Dispose``` on the ```ServerClient``` object and removes any of their channels/memberships.

On the client side, similarly, all of the clients are instances of WatsonTcp and WatsonWebsocket, which also have callbacks should the connection to the server be severed.  These point to ```WatsonServerConnected``` which just sets the boolean indicating that the server is connected.

Internally within WatsonTcpClient the socket is continually polled to see if it is still connected to the server.  If an exception occurs within ```DataReceiver``` or the socket poll fails, in either case the callback indicating a disconnection is used.  

Net-net, the server doesn't have logic to tear down connections outside of ```Dispose```.  The connection state is otherwise relegated to the client implementation, for better or for worse.

When you test with your server implementation and you destructively close the server, does the ```ServerDisconnected``` method get called?  Do you see anything on the screen?  It could be that (somehow) when you destroy your server the connections are being hung rather than dropped (which would be strange).  I don't think calling ```Dispose()``` would leave the connections in a half-open/half-closed or otherwise weird state.

BTW I'll be offline for a few hours but back online later!

**Comment by mpenna** [comment] 2019-09-04 00:12
There's a `ServerStopped` callback exposed by the `ServerCallbacks` class. Are you referring to that one? 

This `ServerStopped` callback is the one that I have tied to a handler on the server host script, but it is not being fired: 

```C#
    private void StartServer()
    {
        Debug.Log("Attempting to start server...");

        _server?.Dispose();

        var config = ServerConfiguration.Default();
        config.TcpServer.Debug = true;

        _server = new Server(config)
        {
            Callbacks =
            {
                MessageReceived = MessageReceived,
                ServerStopped = ServerStopped,
                ClientConnected = ClientConnected,
                ClientLogin = ClientLogin,
                ClientDisconnected = ClientDisconnected
            }
        };

        Debug.Log($"Server running at {config.TcpServer.Ip}:{config.TcpServer.Port}");
    }

    private bool ServerStopped()
    {
        Debug.Log("[ServerStopped] Server has stopped");
        return true;
    }

```

**Comment by jchristn** [comment] 2019-09-04 03:46
Hi @mpenna, I think I have a workaround, at least for ClientTest, for the time being.

I changed the positioning of the try/catch block inside of MaintainConnection and reset the client object back to null when an exception was encountered.

Now, it continually retries, at least on my end.

```
        static void MaintainConnection()
        {
            bool firstRun = true;

            while (true)
            {
                try
                {
                    if (firstRun)
                    {

                    }
                    else
                    {
                        firstRun = false;
                        Thread.Sleep(5000);
                    }

                    if (config == null)
                    {
                        config = ClientConfiguration.Default();
                        config.ClientGUID = Guid.NewGuid().ToString();
                        config.Email = config.ClientGUID;
                        config.Name = config.ClientGUID;
                        config.ServerGUID = "00000000-0000-0000-0000-000000000000";
                        config.SyncTimeoutMs = 30000;

                        config.TcpServer = new ClientConfiguration.TcpServerSettings();
                        config.TcpServer.Debug = true;
                        config.TcpServer.Enable = true;
                        config.TcpServer.Ip = "127.0.0.1";
                        config.TcpServer.Port = 8000;
                    }

                    if (client == null || !client.Connected || !client.LoggedIn)
                    {
                        Console.WriteLine("Attempting to connect to server");
                        if (client != null) client.Dispose();

                        client = new Client(config);

                        client.Callbacks.AsyncMessageReceived = AsyncMessageReceived;
                        client.Callbacks.SyncMessageReceived = SyncMessageReceived;
                        client.Callbacks.ServerDisconnected = ServerDisconnected;
                        client.Callbacks.ServerConnected = ServerConnected;
                        client.Callbacks.ClientJoinedServer = ClientJoinedServer;
                        client.Callbacks.ClientLeftServer = ClientLeftServer;
                        client.Callbacks.ClientJoinedChannel = ClientJoinedChannel;
                        client.Callbacks.ClientLeftChannel = ClientLeftChannel;
                        client.Callbacks.SubscriberJoinedChannel = SubscriberJoinedChannel;
                        client.Callbacks.SubscriberLeftChannel = SubscriberLeftChannel;
                        client.Callbacks.ChannelCreated = ChannelCreated;
                        client.Callbacks.ChannelDestroyed = ChannelDestroyed;

                        Console.WriteLine("Client connected, logging in");
                        Message response;
                        if (!client.Login(out response))
                        {
                            Console.WriteLine("Unable to login, retrying");
                        }
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.ToString());
                    client = null;
                }
            }
        }
```

Please let me know if this helps get past at least the first hurdle.  I need to amend WatsonTcp to allow a connection timeout.  There could still be cases where a re-attempt could hold up the reconnection logic until the attempt times out, at least for now.

Cheers, Joel

**Comment by mpenna** [comment] 2019-09-04 13:42
Hi @jchristn I have applied the new snippet but unfortunately it didn't make any difference. Must be something deeper in the way the teardown is occurring. From what I can tell by the looks of the lingering exchange ports when we stop the server while a client is connected, I would say that something (most probably due to the fact it is being hosted inside a Unity3D app) is preventing the server from sending the LAST_ACK to the clients before itself goes away. 

Proto    Local Address        Foreign Address        State
TCP       127.0.0.1:3314       127.0.0.1:8000           CLOSE_WAIT
TCP       127.0.0.1:8000       127.0.0.1:3314           FIN_WAIT_2

From what I could gather of the TCP protocol, FIN_WAIT_2 is the state of a host who is waiting for the final LAST_ACK to be sent by the host on the other side of the pipe in order to properly shut down the connection. It seems that this last signal never arrives.

BTW Due to other engagements, I'll have to table this discussion for a bit later. I'll pick up on this thread again in a couple of days. Hope you can figure out something in the meantime. Thanks for all the help and effort!

**Comment by jchristn** [comment] 2019-09-05 00:49
Thanks @mpenna and totally understood.  This will take me a few days to update - I'm in the process of updating the lower layers (i.e. WatsonTcp) and some of those changes will zombie through the BigQ code.  Will keep you posted.

**Comment by jchristn** [comment] 2019-09-07 01:52
Hi @mpenna just wanted to let you know I was able to get some fixes into the lower layers (WatsonTcp and WatsonWebsocket) and am integrating those changes (along with a host of other enhancements/improvements) into BigQ now.  I hope to have an update tonight.  There will be breaking changes from the previous version, but shouldn't be too terribly large.  Will keep you posted.  Thanks for your patience, and if this doesn't do it, I'll do my best to spin up an environment similar to that of your app to see if I can reproduce further.  Thanks, Joel

**Comment by jchristn** [comment] 2019-09-07 04:10
Hi @mpenna I may have resolved the issue, though I haven't tried with your specific environment.  Please refer to this commit: https://github.com/bigqio/bigq/commit/3c8071444a7d434e5c41781bbaabfbcc430b1a15

The updates have been pushed to NuGet (Client: https://www.nuget.org/packages/BigQ.Client, and Server: https://www.nuget.org/packages/BigQ.Server)

Note that there are breaking changes.  I've updated the README in the master branch, but they should be really self-explanatory.  

Please let me know if the issue persists after attempting the upgrade!

Thanks, Joel

**Comment by jchristn** [comment] 2019-09-08 01:16
Hi @mpenna I found one more fix I need to put in, working on it tonight.  Will update code and NuGet as soon as its ready.

**Comment by jchristn** [comment] 2019-09-08 02:01
Hi @mpenna just a quick heads-up, I think I have this fixed in both the graceful (client dispose) as well as ungraceful (ctrl-c) cases.  I've updated to release v3.0.2 and committed to github.

As an aside, interestingly enough, this issue came up *while* I was working on yours, which is an issue with the underlying TCP client/server implementation: https://github.com/jchristn/WatsonTcp/issues/31

So I'm hoping that this was at least part of it.  In any case, please let me know if v3.0.2 doesn't resolve the issue for you.  Thanks!

NuGet (server): https://www.nuget.org/packages/BigQ.Server/3.0.2
NuGet (client): https://www.nuget.org/packages/BigQ.Client/
Commit: https://github.com/bigqio/bigq/commit/446fd844bb0437cea1e2f5627f62eaa99115a3eb

**Comment by jchristn** [comment] 2019-09-10 01:11
Minor update again @mpenna - another fix went in on the disconnect issues and NuGet was updated to v3.0.3.1.  Please give it a whirl and let me know if the issue persists!  I'll go ahead and close this issue for now as it seems to be reliable under five different scenarios:
 
- **Server-side Dispose** - Graceful termination of all client connections
- **Server-side Client Removal** - Graceful termination of one client connection
- **Server-side Termination** - Abrupt termination due to process abort or CTRL-C
- **Client-side Dispose** - Graceful termination of a client connection
- **Client-Side Termination** - Abrupt termination due to process abort or CTRL-C

NuGet (server): https://www.nuget.org/packages/BigQ.Server/3.0.3.1
NuGet (client): https://www.nuget.org/packages/BigQ.Client/3.0.3.1

**Closed by jchristn** 2019-09-10 01:11 UTC
